### ISSUE TITLE
openFyde Android bug

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-edge2-openfyde#1]
It's the only bug I have found and Idk how to fix it.
https://ody.sh/nOHEpcjBVD

**Comment by Damenly** [comment]
It happened on my side too. If you change DPI, it happens.

**Comment by DarkevilPT** [comment]
> It happened on my side too. If you change DPI, it happens.

But idk how to fix it. I once did a reset to the Android system by luck and fixed it but as it happens randomly I not always can reset it.

**Comment by davrdz25** [comment]
When I start android applications, there is a bug where the window display is not displayed correctly, it only displays correctly if I change the size of the window, also if there is another application running, the background bar is hidden

Bottombar hidden
![Screenshot 2023-06-01 13 40 01](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/ab412545-3c39-4ecf-a05c-5a32e38dc638)

Bottombar not hidden if window not maximized
![Screenshot 2023-06-01 13 40 22](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/041c2999-a600-4e03-a8a9-60372c63d65a)

App not displayed correctly, there is a bottom portion, transparent
![Screenshot 2023-06-01 13 40 34](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/c5160ff8-35a6-4709-8f3d-2502ba45175f)

App resized and displayed correctly
![Screenshot 2023-06-01 13 40 44](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/a9fda0af-9c8b-4314-846d-001b8e576cd0)

**Comment by Damenly** [comment]
> When I start android applications, there is a bug where the window display is not displayed correctly, it only displays correctly if I change the size of the window, also if there is another application running, the background bar is hidden
> 
> Bottombar hidden ![Screenshot 2023-06-01 13 40 01](https://user-images.githubusercontent.com/61218671/242695124-ab412545-3c39-4ecf-a05c-5a32e38dc638.png)
> 
> Bottombar not hidden if window not maximized ![Screenshot 2023-06-01 13 40 22](https://user-images.githubusercontent.com/61218671/242695283-041c2999-a600-4e03-a8a9-60372c63d65a.png)
> 
> App not displayed correctly, there is a bottom portion, transparent ![Screenshot 2023-06-01 13 40 34](https://user-images.githubusercontent.com/61218671/242695688-c5160ff8-35a6-4709-8f3d-2502ba45175f.png)
> 
> App resized and displayed correctly ![Screenshot 2023-06-01 13 40 44](https://user-images.githubusercontent.com/61218671/242695832-a9fda0af-9c8b-4314-846d-001b8e576cd0.png)

Yeah. There are window issues our ArcHero team is working on.
Feel free to report weird bugs, we will try to solve the theme.

Thanks for your feedback.

**Comment by davrdz25** [comment]
In ooenfyde r114 still he issue wen apone android app, not shown full app
![Screenshot 2023-07-28 14 32 15](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/d97b16d8-17ca-4737-9c04-da7c3443fc5e)

**Comment by davrdz25** [comment]
In tabe md, andrid apps like mSetttings or MicroG settings shown in portrait mode, this happens in other apps like Facebook orn APKPure
![Screenshot 2023-07-28 14 45 41](https://github.com/openFyde/overlay-edge2-openfyde/assets/61218671/31dfbf1d-b4a6-4e63-9124-55e07fdd84f6)

**Comment by DarkevilPT** [comment]
> In tabe md, andrid apps like mSetttings or MicroG settings shown in portrait mode, this happens in other apps like Facebook orn APKPure ![Screenshot 2023-07-28 14 45 41](https://user-images.githubusercontent.com/61218671/256938304-31dfbf1d-b4a6-4e63-9124-55e07fdd84f6.png)
> 
> Android notifications, shown in incorrect orientation

I believe u can disable the rotating thing.. and also if you resise the windows it kinda fixes them ( not always not permanently but yeah ... ).

**Comment by davrdz25** [comment]
> > In tabe md, andrid apps like mSetttings or MicroG settings shown in portrait mode, this happens in other apps like Facebook orn APKPure ![Screenshot 2023-07-28 14 45 41](https://user-images.githubusercontent.com/61218671/256938304-31dfbf1d-b4a6-4e63-9124-55e07fdd84f6.png)
> > Android notifications, shown in incorrect orientation
> 
> I believe u can disable the rotating thing.. and also if you resise the windows it kinda fixes them ( not always not permanently but yeah ... ).

I tried to disable but when Press the Button, nothin happened and still activated

**Comment by DarkevilPT** [comment]
Seems that overall this issue has been fixed.
